image: docker:latest

services:
  - docker:dind
stages:
  - build

variables:
  PROJECT: schoolsaas
  CI_IMAGE_TAG: alpha
  CI_REGISTRY: harbor.godlyobeng.com

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build_backend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/$PROJECT/backend:$CI_IMAGE_TAG ./backend -f Dockerfile
    - docker push $CI_REGISTRY/$PROJECT/backend:$CI_IMAGE_TAG

build_frontend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/$PROJECT/frontend:$CI_IMAGE_TAG ./frontend -f Dockerfile
    - docker push $CI_REGISTRY/$PROJECT/frontend:$CI_IMAGE_TAG
