image: gcr.io/kaniko-project/executor:latest

stages:
  - init
  - build

variables:
  PROJECT: schoolsaas
  CI_IMAGE_TAG: alpha
  CI_REGISTRY: harbor.godlyobeng.com
  DOCKER_CONFIG: /kaniko/.docker/

init_script:
  image: busybox:latest
  stage: init
  tags:
    - kubernetes
  script:
    - mkdir .docker/
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > .docker/config.json
  artifacts:
    paths:
      - .docker/

build_backend:
  stage: build
  tags:
    - kubernetes
  script:
    - mkdir -p /kaniko/.docker
    - cp .docker/config.json /kaniko/.docker/config.json
    - /kaniko/executor
      --context ./backend
      --dockerfile ./backend/Dockerfile
      --destination $CI_REGISTRY/$PROJECT/backend:$CI_IMAGE_TAG

build_frontend:
  stage: build
  tags:
    - kubernetes
  script:
    - mkdir -p /kaniko/.docker
    - cp .docker/config.json /kaniko/.docker/config.json
    - /kaniko/executor
      --context ./frontend
      --dockerfile ./frontend/Dockerfile
      --destination $CI_REGISTRY/$PROJECT/frontend:$CI_IMAGE_TAG
