image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

stages:
  - init
  - build
  - manifest

variables:
  PROJECT: schoolsaas
  CI_IMAGE_TAG: alpha
  CI_REGISTRY: harbor.godlyobeng.com
  DOCKER_CONFIG: /kaniko/.docker/
  ARCHITECTURES: "amd64,arm64"

init_script:
  image: busybox:latest
  stage: init
  tags:
    - kubernetes
  script:
    - mkdir .docker/
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > .docker/config.json
  artifacts:
    paths:
      - .docker/

build_backend:
  stage: build
  tags:
    - kubernetes
  script:
    - mkdir -p /kaniko/.docker
    - cp .docker/config.json /kaniko/.docker/config.json
    - |
      for ARCH in ${ARCHITECTURES//,/ }; do
        /kaniko/executor --no-cache \
          --context ./backend \
          --dockerfile ./backend/Dockerfile \
          --destination $CI_REGISTRY/$PROJECT/backend:${CI_IMAGE_TAG}-$ARCH \
          --build-arg ARCH=$ARCH
      done

build_frontend:
  stage: build
  tags:
    - kubernetes
  script:
    - mkdir -p /kaniko/.docker
    - cp .docker/config.json /kaniko/.docker/config.json
    - |
      for ARCH in ${ARCHITECTURES//,/ }; do
        /kaniko/executor --no-cache \
          --context ./frontend \
          --dockerfile ./frontend/Dockerfile \
          --destination $CI_REGISTRY/$PROJECT/frontend:${CI_IMAGE_TAG}-$ARCH \
          --build-arg ARCH=$ARCH
      done

create_and_push_manifest:
  stage: manifest
  image: ghcr.io/estesp/manifest-tool:latest
  script:
    - |
      manifest-tool push from-args \
        --platforms linux/amd64,linux/arm64 \
        --template $CI_REGISTRY/$PROJECT/backend:${CI_IMAGE_TAG}-ARCH \
        --target $CI_REGISTRY/$PROJECT/backend:$CI_IMAGE_TAG
    - |
      manifest-tool push from-args \
        --platforms linux/amd64,linux/arm64 \
        --template $CI_REGISTRY/$PROJECT/frontend:${CI_IMAGE_TAG}-ARCH \
        --target $CI_REGISTRY/$PROJECT/frontend:$CI_IMAGE_TAG
  dependencies:
    - build_backend
    - build_frontend
