image: gcr.io/kaniko-project/executor:latest

stages:
  - build

variables:
  PROJECT: schoolsaas
  CI_IMAGE_TAG: alpha
  CI_REGISTRY: harbor.godlyobeng.com
  DOCKER_CONFIG: /kaniko/.docker/

before_script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

build_backend:
  stage: build
  tags:
    - kubernetes
  script:
    - /kaniko/executor
      --context ./backend
      --dockerfile ./backend/Dockerfile
      --destination $CI_REGISTRY/$PROJECT/backend:$CI_IMAGE_TAG

build_frontend:
  stage: build
  tags:
    - kubernetes
  script:
    - /kaniko/executor
      --context ./frontend
      --dockerfile ./frontend/Dockerfile
      --destination $CI_REGISTRY/$PROJECT/frontend:$CI_IMAGE_TAG
