# Generated by Django 5.1.3 on 2025-03-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicationmodules_alter_school_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_current_school_member',
            field=models.BooleanField(default=True),
        ),
    ]
