# Generated by Django 5.1.3 on 2025-04-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_current_school_member'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'email')},
        ),
    ]
